### ISSUE TITLE
Add testing resources 

### ISSUE THREAD

**Issue by m1yag1** [pyslackers/learning-resources#11]
Put Brian Okken's book, Obey the testing goat blog/book, and the Test and Code podcast.

**Comment by LuisArteaga** [comment]
Done.
Please check PR.

**Comment by ovv** [comment]
Thanks @LuisArteaga 

FYI you can close issue automatically from a PR if you include `fix #11` in the comment.
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by LuisArteaga** [comment]
@ovv ok, got it.
